account/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
     
     path('login/',
          auth_views.LoginView.as_view(template_name='login.html'),
          name='login'),

     path('logout/',
          auth_views.LogoutView.as_view(template_name='logout.html'),
          name='logout'),
]

strapp/urls.py
from django.urls import path
from . import views

app_name = 'strapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path ('bulletin/', views.BulletinView.as_view(), name='bulletin'),

    path ('bulletinform/', views.BulletinFormView.as_view(), name='bulletin_form'),

    path('character-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'character_detail'),

    path('character/<str:category>',
         views.CategoryView.as_view(),
         name = 'character_cat'),

    path('characterform/', views.CharacterFormView.as_view(), name='character_form'),

    path('character_done/',
         views.CharacterSuccessView.as_view(),
         name='character_done'),

    path('contact/', views.ContactView.as_view(), name='contact'),

    path('character/<int:pk>/delete/',
         views.CharacterDeleteView.as_view(),
         name = 'character_delete'),
]

strategy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('strapp.urls')),

    path('', include('account.urls')),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),
         name = 'password_reset'),
    
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"),
         name = 'password_reset_done'),
    
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"),
         name = 'password_reset_confirm'),
    
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"),
         name = 'password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )

account/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

account/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

account/views.py
from django.shortcuts import render

from django.views.generic import CreateView, TemplateView

from .forms import CustomUserCreationForm

from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy('account:signup_success')

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name = "signup_success.html"

account/templates/login.html
{% load static %}

<!doctype html>
<html lang="ja" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>Lod in</title>

    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />

    

    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static "css/signin.css" %}" rel="stylesheet">
  </head>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<main class="form-signin w-100 m-auto">
  {% if form.errors %}
    <p style="color: red">ユーザー名とパスワードが一致しません。</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <img class="mb-4" src={% static "img/bootstrap-logo.svg" %} alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <label for="Username" class="visually-hidden">User name</label>
    <input type="text"
    name="username"
    id="id_username"
    maxlength="150"
    autocapitalize="none"
    autocomplete="username"
    class="form-control"
    placeholder="ユーザー名"
    required autofocus>

    <label for="Password" class="visually-hidden">Password</label>
    <input type="password"
    name="password"
    id="id_password"
    autocomplete="current-password"
    class="form-control"
    placeholder="パスワード"
    required autofocus>

    <input class="w-100btn btn-lg btn-primary" type="submit" value="ログイン">
    <br><br>
    <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a></p>
    <input type="hidden"
    name="next"
    value="{% url 'strapp:index' %}">

  </form>
</main>
    </body>
</html>

account/templates/logout.html
{% extends 'base.html' %}

{% block title %}Log out{% endblock %}

    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
            <h3>ログアウトしました</h3>
            <p><a href="{% url 'strapp:index' %}"></a></p>
        {% endblock %}
            </div>
        </div>
    </div>

account/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか？</h3>
                <p>
                    登録済みのメールアドレスを入力してください。
                    パスワードリセットのリンクを記載したメールをすぐにお届けします。
                </p>
                <br>
                <form action="" method="POST" class="text-center">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="メールを受け取る" /><br>
                </form>
                <br>
                <a href="{% url 'strapp:index' %}">Photo Gallery</a>
                <hr>
            </div>
        </div>
    </div>
    {% endblock %}

account/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
            }
        </style>
    </head>

    <body>
        <div class="pad">
            <h2>パスワードがリセットされました。</h2>
            <P>
                Your Password has been set. You may go ahead and login
            </P>
            <br>
            <a href="{% url 'strapp:index' %}">Photo Galleryのトップページへ</a>
        </div>
    </body>
</html>

account/templates/password_reset_form.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
            }
        </style>
    </head>

    <body>
        <div class="pad">
            <h2>Photo Gallery</h2>
            <h4>
                新しいパスワードを2回入力してください。これにより、
                正しく入力できたことが確認されます。
            </h4>
            <br />

            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <inputn type="submit" value="パスワードリセット"/>
            </form>
        </div>
    </body>
</html>

account/templates/password_reset_sent.html
{% extends 'base.html' %}

{% block title %}Send password reset{% endblock %}

    {% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2 py-4">
                <h5>パスワードのリセット手順をメールで送信しました。
                    メールはすぐに届きます。
                </h5>
                <br>
                <h6>
                    メールが届かない場合は、登録済みのメールアドレスであるかを
                    確認し、迷惑メールフォルダーも確認してみてください。
                </h6>
                <a href="{% url 'strapp:index' %}">Photo Gallery</a>
            </div>
        </div>
    </div>
    {% endblock %}

account/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sing up{% endblock %}

    {% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h3>サインアップ</h3>
                <form method = "post">
                    {% csrf_token %}
                    {% for field in form %}
                    <p>
                        {{ field.label_tag }}<br>
                        {{ field }}

                        {% if field.help_text %}
                            <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}

                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    <p style="color: red">
                        ※メールアドレスはパスワードをリセットする際に必要になりますので、
                        登録をお願いします。
                    </p>
                    <input type="submit" value="Sign up">
                </form>
                <br>
                <p><a href="{% url 'strapp:index' %}">
                    登録をやめてトップページに戻る</a>
                </p>
            </div>
        </div>
    </div>
    {% endblock %}

account/templates/signup_success.html
{% extends 'base.html' %}

{% block title %}Registration Complete{% endblock %}

    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
                <h3>登録が完了しました</h3>
                <p><a herf="{% url 'account:login' %}">ログインはこちら</a></p>
            </div>
        </div>
    </div>
    {% endblock %}