strapp/urls.py
from django.urls import path
from . import views

app_name = 'strapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path ('bulletin/', views.BulletinView.as_view(), name='bulletin'),

    path ('bulletinform/', views.BulletinFormView.as_view(), name='bulletin_form'),

    path('character-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'character_detail'),

    path('character/<str:category>',
         views.CategoryView.as_view(),
         name = 'character_cat'),

    path('characterform/', views.CharacterFormView.as_view(), name='character_form'),

    path('character_done/',
         views.CharacterSuccessView.as_view(),
         name='character_done'),

    path('contact/', views.ContactView.as_view(), name='contact'),

    path('character/<int:pk>/delete/',
         views.CharacterDeleteView.as_view(),
         name = 'character_delete'),
]

strategy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('strapp.urls')),

    path('', include('account.urls')),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),
         name = 'password_reset'),
    
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"),
         name = 'password_reset_done'),
    
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"),
         name = 'password_reset_confirm'),
    
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"),
         name = 'password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )

strapp/models.py
from django.db import models

from account.models import CustomUser

class Bulletin(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )

    text = models.TextField(
        verbose_name='コメント'
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    def __str__ (self):
        return self.user

class Characters(models.Model):
    CATEGORY = (('millennium', 'ミレニアム'),
                ('trinity', 'トリニティ'),
                ('gehenna', 'ゲヘナ'),
                ('abydos', 'アビドス'),
                ('hyakki', '百鬼夜行'),
                ('redwinter', 'レッドウィンター'),
                ('valkyrie', 'ヴァルキューレ'),
                ('srt', 'SRT'),
                ('sengaikyo', '山海経'),
                ('arius', 'アリウス'))

    category = models.CharField(
        verbose_name='学園',
        max_length=50,
        choices = CATEGORY
    )

    name = models.CharField(
        verbose_name='名前',
        max_length=200
    )

    image = models.ImageField(
        verbose_name='立ち絵',
        upload_to = 'photos'
    )

    age = models.IntegerField(
        verbose_name='年齢',
        null=True,
        blank=True
    )
    
    birthday = models.DateField(
        verbose_name='誕生日'
    )

    height = models.IntegerField(
        verbose_name='身長'
    )
    
    hobby = models.CharField(
        verbose_name='趣味',
        max_length=50
    )

    voice = models.CharField(
        verbose_name='CV',
        max_length=20
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    def __str__ (self):
        return self.name

strapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import Characters, Bulletin

class BulletinForm(ModelForm):
    class Meta:
        model = Bulletin
        fields = ['text']

class CharacterForm(ModelForm):
    class Meta:
        model = Characters
        fields = ['category', 'name','image', 'age', 'birthday', 'height', 'hobby', 'voice']

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

strapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, FormView, CreateView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Characters, Bulletin
from .forms import CharacterForm, ContactForm, BulletinForm
from django.contrib import messages
from django.core.mail import EmailMessage

class IndexView(ListView):
    template_name = 'index.html'
    queryset = Characters.objects.order_by('-posted_at')

class BulletinView(ListView):
    template_name = 'bulletin.html'
    queryset = Bulletin.objects.order_by('-posted_at')

class DetailView(DetailView):
    template_name = 'detail.html'
    model = Characters

class CategoryView(ListView):
    template_name = 'index.html'

    def get_queryset(self):
        category_id = self.kwargs['category']
        categories = Characters.objects.filter(
            category=category_id).order_by('-posted_at')
        return categories

@method_decorator(login_required, name='dispatch')

class BulletinFormView(CreateView):
    form_class = BulletinForm
    template_name = "bulletin_form.html"
    success_url = reverse_lazy('strapp:bulletin')

    def form_valid(self, form):
        text_data = form.save(commit=False)
        text_data.user = self.request.user
        text_data.save()
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')

class CharacterFormView(CreateView):
    form_class = CharacterForm
    template_name = "character_form.html"
    success_url = reverse_lazy('strapp:character_done')

    def form_valid(self, form):
        character_data = form.save(commit=False)
        character_data.user = self.request.user
        character_data.save()
        return super().form_valid(form)

class CharacterSuccessView(TemplateView):
    template_name = 'character_success.html'

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('strapp:contact')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        message = \
            '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:{3}'\
            .format(name, email, title, message)
        from_email = 'xxxx@gmail.com'
        to_list = ['guitaizuochuan@gmail.com']
        message = EmailMessage(subject=subject,
                                body=message,
                                from_email=from_email,
                                to=to_list,
                                )
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

class CharacterDeleteView(DeleteView):
    model = Characters
    template_name = 'character_delete.html'
    success_url = reverse_lazy('strapp:index')

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
        

strapp/templates/bulletin.html
{% extends 'base.html' %}

{% block title %}ブルアカまとめ{% endblock %}

    {% block contents %}

    <h2>掲示板</h2>

    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>ユーザー</th>
                    <th>コメント</th>
                    <th>投稿日時</th>
                </tr>
            </thead>
            {% for text in object_list %}
            <tbody>
                <tr>
                    <td>{{ text.user }}</td>
                    <td>{{ text.text }}</td>
                    <td>{{ text.posted_at }}</td>
                </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
    
    {% endblock %}

strapp/templates/bulletin_form.html
{% extends 'base.html' %}

{% block title %}ブルアカまとめ{% endblock %}

    {% block contents %}

    <h2>コメント書き込み</h2>

    <div class="container">
        <div class="row">
            <div class="my-div-style">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
    
                    {{ form.non_field_errors }}
    
                    {% for field in form %}
                        <div class="form-group row">
                            <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                                <strong>{{ field.label_tag }}</strong>
                            </label>
                            <div class="col-sm-8">
                                {{ field }}
                                {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
    
                    <div class="offset-sm-4 col-sm-8">
                        <button type="submit">投稿する</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% endblock %}

strapp/templates/character_form.html
{% extends 'base.html' %}

{% block title %}キャラクター登録{% endblock %}

{% block contents %}

<h2>キャラクター登録</h2>

<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button type="submit">投稿する</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

strapp/templates/character_list.html
<h2>キャラクター一覧</h2>
<div class="table-responsive small">
  <table class="table-striped table-sm back">
    <thead>
      <tr>
        <th scope="col">立ち絵</th>
        <th scope="col">キャラクター</th>
        <th scope="col">学園</th>
        <th scope="col">年齢</th>
        <th scope="col">誕生日</th>
        <th scope="col">身長</th>
        <th scope="col">趣味</th>
        <th scope="col">CV.</th>
      </tr>
    </thead>
    <tbody>
      {% for record in object_list %}
      <tr>
        <td><img src="{{ record.image.url }}"
          width="20%" height="20%"
          xmlns="http://www.w3.org/2000/svg"
          role="img" aria-label="Placeholder: Thumbnail"
          preserveAspectRatio="xMidYMid slice"
          focusable="false">
          <title>Placeholder</title>
        </td>
          <rect width="20%" height="20%" fill="#55595c"/>
        <td><a href="{% url 'strapp:character_detail' record.pk %}">{{ record.name }}</a></td>
        <td>{{ record.get_category_display }}</td>
        {% if record.age == None %}
        <td>不明</td>
        {% else %}
        <td>{{ record.age }}歳</td>
        {% endif %}
        <td>{{ record.birthday|date:"n月j日" }}</td>
        <td>{{ record.height }}cm</td>
        <td>{{ record.hobby }}</td>
        <td>{{ record.voice }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

strapp/templates/character_success.html
{% extends 'base.html' %}

{% block title %}Success{% endblock %}

    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>登録が完了しました！</h4>
                <p><a href="{% url 'strapp:character_form' %}">もう一度登録する</a></p>
            </div>
        </div>
    </div>
    {% endblock %}

strapp/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Contact{% endblock %}
        <!-- Page Header-->
        {% block header %}
        <header>
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
        {% block contents %}
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <strong>連絡を取りたいですか？
                            以下のフォームに記入してメッセージを送信してください。
                            できるだけ早くご連絡お願いします。
                        </strong>

                        {% if messages %}
                        <ul class="list-unstyled" style="list-style: none;">

                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                            
                        </ul>
                        {% endif %}

                        <div class="my-5">
                            <form method="post">
                                {% csrf_token %}

                                {% for field in form %}
                                <div class="form-floating">
                                    <div class="form-group floating-label-form-group controls">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                {% endfor %}

                                <br>
                                <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        </main>
        {% endblock %}
        <!-- Footer-->

strapp/templates/detail.html
{% extends 'base.html' %}

{% block title %}キャラクター詳細{% endblock %}

    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{ object.name }}</h2>
                <br>
                <p><img src="{{ object.image.url }}"></img></p>
                <br>
                <strong>年齢</strong>
                {% if object.age == None %}
                <p>不明</p>
                {% else %}
                <p>{{ object.age }}歳</p>
                {% endif %}
                <br>
                <strong>誕生日</strong>
                <p>{{ object.birthday|date:"n月j日" }}</p>
                <br>
                <strong>身長</strong>
                <p>{{ object.height }}cm</p>
                <br>
                <strong>趣味</strong>
                <p>{{ object.hobby }}</p>
                <br>
                <strong>声優</strong>
                <p>{{ object.voice }}</p>
                {% if request.user == object.user %}
                <form method="POST">
                <a href="{% url 'strapp:character_delete' object.pk %}"
                class="btn btn-primary my-2">削除する</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

strapp/templates/index.html
{% extends 'base.html' %}

{% block title %}ブルアカまとめ{% endblock %}

    {% block contents %}

    {% include 'character_list.html' %}

    {% endblock %}